PlaygroundMainBundle:
    resource: "@PlaygroundMainBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

# _wdt:
#     resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
#     prefix:   /_wdt

# _profiler:
#     resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
#     prefix:   /_profiler

# _configurator:
#     resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
#     prefix:   /_configurator
