# PlaygroundMainBundle_homepage:
#     pattern:  /hello/{name}
#     defaults: { _controller: PlaygroundMainBundle:Default:index }
PlaygroundMainBundle_homepage:
  pattern: /
  defaults: { _controller: PlaygroundMainBundle:Main:index }
  requirements:
    _method: GET|POST
