parameters:
   custom_email_validator.class: Playground\MainBundle\Services\Validator\CustomEmailValidator
   notification_sender.class: Playground\MainBundle\Services\Mailer\NotificationSender
services:
#    playground_main.example:
#        class: %playground_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
  playground_main.custom_email_validator:
    class: %custom_email_validator.class%
    arguments: [ @doctrine.orm.entity_manager ]

  playground_main.notification_sender:
    class: %notification_sender.class%
    arguments: [ @mailer, 'subject', 'message' ]