parameters:
#    playground_main.example.class: Playground\MainBundle\Example

services:
#    playground_main.example:
#        class: %playground_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
