parameters:
   custom_email_validator.class: Playground\MainBundle\Validator\CustomEmailValidator

services:
#    playground_main.example:
#        class: %playground_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
  playground_main.custom_email_validator:
    class: %custom_email_validator.class%
    arguments: [ @doctrine.orm.entity_manager ]
